[project]
name = "q-opt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dwave-ocean-sdk>=8.4.0",
    "pandas>=2.3.1",
]
